# Generated by Django 4.1.2 on 2022-10-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_image_1_post_post_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preheader',
            field=models.TextField(default='Welcome to my Vilanovella blog. My name is Jon and I just moved from London in the UK to a small town called "Vilanova i la Geltrú" in Spain! On 5th September 2022 my partner Julia, my 4-year-old daughter Zoë, my 1,5-year-old son Adrian and I hopped on a one-way flight to Barcelona airport.'),
            preserve_default=False,
        ),
    ]
