# Generated by Django 4.1.2 on 2022-10-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image_1',
            new_name='hero_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image_7',
        ),
    ]
