# Generated by Django 4.1.2 on 2022-11-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_rename_post_image_1_post_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
